data:
  dataset: fashionMNIST # mnist   
train:
  batch_size: 64
  lr: 0.0002
  n_epochs: 100
  num_workers: 4 # change this based on number of cores on your CPU. 4 is sufficient for 1 gpu. If unsure leave at 1.  
network:
  model: gan # vae, gan, diffusion
  hidden_dim: 1024 # used for VAE and gan
  latent_dim: 64 # used for VAE or gan
vae:
  vae_recon_loss: l2  # l1 or l2
  beta: 0.5
diffusion:
  time_dim: 128
  timesteps: 500
optimizer:
  type: 'adamw' # adamw or sgd
  weight_decay: 0.0 #0.001
gan:
  leaky: False
